Add support for moving index to end of order list during deletion
DataDog/datadog-sync-cli pull request #233
Opened 2024-04-23 19:41 UTC by skarimo

2024-04-26 12:23 UTC, luchenyuxx approved these changes

2024-04-26 12:45 UTC, luchenyuxx reviewed
Is it possible to add an unit test for this?

2024-04-30 09:05 UTC, luchenyuxx approved these changes

2024-05-01 19:15 UTC, tim-chaplin-dd requested changes

2024-05-01 19:15 UTC, tim-chaplin-dd commented on tests/integration/resources/test_logs_indexes.py
> +        req = urllib.request.Request(
I think to prove that the order changed you also need to call this prior to `sync` and assert that `first_index` comes first in the ordering.

2024-05-01 19:15 UTC, tim-chaplin-dd commented on tests/integration/resources/test_logs_indexes.py
> +        first_index = list(source_resources.keys())[0]
Where does the data for this test come from? It'd be easier to visually verify that it's correct if it was hardcoded in the test itself. I think the test trivially passes if `source_resources` is length 1, or if all of its elements are identical, and it's not clear whether that's the case here.

2024-05-01 19:36 UTC, tim-chaplin-dd commented on tests/integration/resources/test_logs_indexes.py
> +        req = urllib.request.Request(
Nevermind, Sherzod explained the cassette thing to me offline, I don't think this comment is relevant.

2024-05-03 14:07 UTC, merged