Add support for `authn_mappings`
DataDog/datadog-sync-cli pull request #255
Opened 2024-06-14 17:43 UTC by skarimo

APITL-914

2024-06-14 19:37 UTC, brett0000FF submitted a review, later dismissed

2024-06-14 20:37 UTC, nkzou requested changes

2024-06-14 20:37 UTC, nkzou commented on scripts/cleanup_org.py
> +    def cleanup_authn_mappigns(
```suggestion
    def cleanup_authn_mappings(
```

2024-06-14 20:37 UTC, nkzou commented on scripts/cleanup_org.py
> +        self.cleanup_authn_mappigns()
```suggestion
        self.cleanup_authn_mappings()
```

2024-06-24 18:01 UTC, jack-edmonds-dd approved these changes

2024-06-27 17:32 UTC, merged